# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: WebApp-ARM-PrevImage
version: 1.0.0
summary: Azure Web App Environment
description: Deploys an Azure Web App without a data store
runner: acradamasmarimageupdates.azurecr.io/deployment-environments/runners/arm:dual-6.0.0
templatePath: azuredeploy.json

parameters:
  - id: name
    name: Name
    description: 'Name of the Web App.'
    type: string
    required: true
